services:
  # Combined Service
  - type: web
    name: esports-team-finder
    env: python
    buildCommand: chmod +x build.sh && ./build.sh  # Ensure build script is executable
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REACT_APP_API_URL
        value: https://esports-team-finder.onrender.com
      - key: CI
        value: "false"
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: NODE_OPTIONS
        value: "--max_old_space_size=2048"
