services:
  # Backend API service
  - type: web
    name: esports-team-finder-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: CORS_ORIGINS
        value: https://esports-team-finder.onrender.com

  # Frontend service
  - type: static
    name: esports-team-finder-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://esports-team-finder-api.onrender.com
