services:
  # Backend API service
  - type: web
    name: esports-team-finder
    env: python
    region: ohio
    plan: free
    buildCommand: bash render_build.sh
    startCommand: cd backend && python main.py
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.x
      - key: MONGODB_URL
        fromDatabase:
          name: esports-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: CI
        value: "false"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: PYTHONPATH
        value: backend
      - key: PUBLIC_URL
        value: /
    autoDeploy: true

databases:
  - name: esports-db
    databaseName: esports
    plan: free
