services:
  # Backend API service
  - type: web
    name: esports-team-finder-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd ../frontend && npm install && npm run build
      cd ../backend
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: PORT
        value: 8000
